# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bilgi_girisi.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_baglanti import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 600)
        Form.setMinimumSize(1100,600)
        Form.setMaximumSize(1100,600)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 40, 721, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.atAdiLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.atAdiLabel.setObjectName("atAdiLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.atAdiLabel)
        self.atAdiLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.atAdiLineEdit.setObjectName("atAdiLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.atAdiLineEdit)
        self.atSahibiLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.atSahibiLabel.setObjectName("atSahibiLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.atSahibiLabel)
        self.atSahibiLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.atSahibiLineEdit.setObjectName("atSahibiLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.atSahibiLineEdit)
        self.atJokeriLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.atJokeriLabel.setObjectName("atJokeriLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.atJokeriLabel)
        self.atJokeriLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.atJokeriLineEdit.setObjectName("atJokeriLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.atJokeriLineEdit)
        self.mesafeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mesafeLabel.setObjectName("mesafeLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mesafeLabel)
        self.mesafeLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mesafeLineEdit.setObjectName("mesafeLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mesafeLineEdit)
        self.kosuCinsiLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kosuCinsiLabel.setObjectName("kosuCinsiLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.kosuCinsiLabel)
        self.kosuCinsiLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kosuCinsiLineEdit.setObjectName("kosuCinsiLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.kosuCinsiLineEdit)
        self.atKilosuLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.atKilosuLabel.setObjectName("atKilosuLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.atKilosuLabel)
        self.atKilosuLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.atKilosuLineEdit.setObjectName("atKilosuLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.atKilosuLineEdit)
        self.sehirLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.sehirLabel.setObjectName("sehirLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sehirLabel)
        self.sehirLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.sehirLineEdit.setObjectName("sehirLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sehirLineEdit)
        self.dereceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dereceLabel.setObjectName("dereceLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.dereceLabel)
        self.dereceLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.dereceLineEdit.setObjectName("dereceLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.dereceLineEdit)
        self.kosSuresiLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kosSuresiLabel.setObjectName("kosSuresiLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.kosSuresiLabel)
        self.kosSuresiLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kosSuresiLineEdit.setObjectName("kosSuresiLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.kosSuresiLineEdit)
        self.tarihLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tarihLabel.setObjectName("tarihLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.tarihLabel)
        self.tarihDateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.tarihDateEdit.setDisplayFormat("dd.MM.yyyy")
        self.tarihDateEdit.setObjectName("tarihDateEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.tarihDateEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



        self.pushButton.clicked.connect(self.veri_yolla)
        self.pushButton_1.clicked.connect(self.temizle)
        self.pushButton_2.clicked.connect(lambda  : self.bilgigiris_kapat(Form))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.atAdiLabel.setText(_translate("Form", "At Adi"))
        self.atSahibiLabel.setText(_translate("Form", "AtSahibi"))
        self.atJokeriLabel.setText(_translate("Form", "At Jokeri"))
        self.mesafeLabel.setText(_translate("Form", "Mesafe"))
        self.kosuCinsiLabel.setText(_translate("Form", "Kosu Cinsi"))
        self.atKilosuLabel.setText(_translate("Form", "At Kilosu"))
        self.sehirLabel.setText(_translate("Form", "Sehir"))
        self.dereceLabel.setText(_translate("Form", "Derece"))
        self.kosSuresiLabel.setText(_translate("Form", "Kos Suresi"))
        self.tarihLabel.setText(_translate("Form", "Tarih"))
        self.pushButton_2.setText(_translate("Form", "Cik"))
        self.pushButton_1.setText(_translate("Form","Temizle"))
        self.pushButton.setText(_translate("Form", "Kaydet"))


    def veri_yolla(self):

        self.db_obje = Db_Islemleri()

        self.db_obje.veri_ekle(self.atAdiLineEdit.text(), self.atSahibiLineEdit.text(), self. atJokeriLineEdit.text(), self.mesafeLineEdit.text(), self. kosSuresiLineEdit.text(), self.atKilosuLineEdit.text(), self.sehirLineEdit.text(), self.dereceLineEdit.text(), self.kosSuresiLineEdit.text(), self.tarihDateEdit.text())
        self.db_obje.con.close()


    def temizle(self):
        self.atAdiLineEdit.clear()
        self.atSahibiLineEdit.clear()
        self.atJokeriLineEdit.clear()
        self.mesafeLineEdit.clear()
        self.kosuCinsiLineEdit.clear()
        self.atKilosuLineEdit.clear()
        self.sehirLineEdit.clear()
        self.dereceLineEdit.clear()
        self.kosSuresiLineEdit.clear()
        self.tarihDateEdit.clear()


    def bilgigiris_kapat(self,Form):

        Form.hide()