# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sorgu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_baglanti import *

class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(1217, 901)
        Form1.setMinimumSize(QtCore.QSize(1217, 901))
        Form1.setMaximumSize(QtCore.QSize(1217, 901))
        self.verticalLayoutWidget = QtWidgets.QWidget(Form1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 1181, 871))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

        self.pushButton.clicked.connect(self.sonuclari_goster)



    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Form"))
        self.label.setText(_translate("Form1", "At Sahibini Girin :"))
        self.pushButton.setText(_translate("Form1", "Sorgula"))



    def sonuclari_goster(self):

        at_sahibi = self.lineEdit.text()
        db = Db_Islemleri()
        liste = db.sorgu_yap(at_sahibi)


        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(len(liste))
        self.tableWidget.setHorizontalHeaderLabels(("At Adi","At Sahibi","At Jokeri","Mesafe","Kosu Cinsi","At Kilosu","Sehir","Derece","Kosma Suresi","Tarih"))

        for i in range(0,len(liste)):
            for j in range(0,10):
                self.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(liste[i][j]))
